# Generated by Django 5.2.7 on 2025-10-24 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
