# Generated by Django 5.2.7 on 2025-10-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(default="male", max_length=10),
        ),
    ]
