# Generated by Django 5.2.7 on 2025-10-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
